name: Release Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
      - name: Configure Git
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          token: '${{ secrets.GH_TOKEN }}'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release
        run: |
          mvn -B -U \
           release:prepare \
           release:perform \
          -s settings.xml \
          -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
          -DscmCommentPrefix="[maven-release-plugin][skip ci]"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}